source: _blog_posts
layouts_dir: layouts
destination: reviews
url: https://pminasandra.github.io/reviews
baseurl: /reviews
permalink: date

#Added stuff from here
source: _papers
layouts_dir: layouts
destination: publications
url: https://pminasandra.github.io/publications
baseurl: /publications
permalink: date
